### ISSUE TITLE
Change how commands are handled

### ISSUE THREAD

**Issue by DakshChan** [UTM-Robotics/discord-auth-bot#6]
**Is your feature request related to a problem? Please describe.**
In the code base, there is a single large function handling all the commands. This is not ideal since we have a large amount of nesting, and a hard-to-read and follow code base

**Describe the solution you'd like**
Switch to using a function per command, see https://github.com/Rapptz/discord.py#bot-example

This breaks down our large function into smaller functions and also removes some of the indentation and nesting

**Describe alternatives you've considered**
Slash commands are another viable approach, although I decided that as a first step, we can keep the existing usage.

**Comment by Jeffzycode** [comment]
Attempted to implement.
